### ISSUE TITLE
CLI throws, no `cekMachineCost` file found

### ISSUE THREAD

**Issue by Banou26** [ImperatorLang/uplc#32]
When trying to use this package's CLI through PIP, it throws with
```
uplc dump myScript.bin --from-cbor
Traceback (most recent call last):
  File "/home/banou/miniconda3/envs/clairvoyance/bin/uplc", line 5, in <module>
    from uplc.__main__ import main
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/__init__.py", line 16, in <module>
    from .tools import parse, eval, dumps, UPLCDialect, flatten, unflatten
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/tools.py", line 66, in <module>
    cek_machine_cost_model: CekMachineCostModel = default_cek_machine_cost_model_plutus_v2(),
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model.py", line 489, in default_cek_machine_cost_model_plutus_v2
    return default_cek_machine_cost_model(PlutusVersion.PlutusV2)
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model.py", line 478, in default_cek_machine_cost_model
    latest_network_config_plutus(plutus_version),
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model.py", line 419, in latest_network_config_plutus
    return latest_network_config()[plutus_version.value]
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model.py", line 415, in latest_network_config
    return load_network_config("latest")
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model.py", line 403, in load_network_config
    for file in latest_network_config_dir.iterdir():
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model_files/latest'
```

Creating a file named `cekMachineCost.json` at `/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model_files/latest` with the contents of: https://github.com/OpShin/uplc/blob/794fd3068c53b9794dc0e2fcc3ed822e033ac958/uplc/cost_model_files/2023-02-14/cost-model-secp-preprod-mainnet.json seems to fix the issue.

**Comment by nielstron** [comment]
Thanks for reporting this. I guess the package does not include the json files, will look into this.

**Comment by nielstron** [comment]
Oh actually the files are present but the symlink "latest" to the latest version does not work. I will fix this in a patch release.

**Comment by nielstron** [comment]
The issue should be fixed in https://github.com/OpShin/uplc/releases/tag/1.0.2, please confirm this :)

**Comment by Banou26** [comment]
Now it seems to throw with
```
uplc dump myScript.bin --from-cbor           
Traceback (most recent call last):
  File "/home/banou/miniconda3/envs/clairvoyance/bin/uplc", line 5, in <module>
    from uplc.__main__ import main
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/__init__.py", line 16, in <module>
    from .tools import parse, eval, dumps, UPLCDialect, flatten, unflatten
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/tools.py", line 66, in <module>
    cek_machine_cost_model: CekMachineCostModel = default_cek_machine_cost_model_plutus_v2(),
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model.py", line 510, in default_cek_machine_cost_model_plutus_v2
    return default_cek_machine_cost_model(PlutusVersion.PlutusV2)
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model.py", line 499, in default_cek_machine_cost_model
    latest_network_config_plutus(plutus_version),
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model.py", line 440, in latest_network_config_plutus
    return latest_network_config()[plutus_version.value]
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model.py", line 436, in latest_network_config
    return load_network_config(datetime.date.today())
  File "/home/banou/miniconda3/envs/clairvoyance/lib/python3.10/site-packages/uplc/cost_model.py", line 413, in load_network_config
    dir_date = datetime.date.fromisoformat(dir.name)
ValueError: Invalid isoformat string: 'latest'
```

Seems like the cost_model expects a date as folder name but `latest` is used instead

**Comment by nielstron** [comment]
I think this should be the result of your manual patch - if you remove the file/folder you added it should work fine again. Alternatively you can install the latest version based off the `dev` branch.

**Comment by Banou26** [comment]
Oh woops, i thought `pip uninstall` would clear that, yup that worked, thanks so much for the quick response.
Also great project, it's the only one that i have found to support all of the UPLC terms properly :)

**Comment by nielstron** [comment]
Thank you! I would assume [the official version ](https://github.com/IntersectMBO/plutus/releases/tag/1.21.0.0) and `aiken` should also support everything but AFAIK the only Python implementation so far.

**Comment by Banou26** [comment]
Trying to dump from bin to UPLC using aiken's CLI, results in a lot of errors / unhandled terms, your dump so far has been perfect.
Haven't tried plutus directly yet. It's a pain to setup, python on the other hand, isn't :).
